
#开发环境
#logging:
#  level:
#    com.lsn.user.mapper: debug
server:
  port: 8080
spring:
  #数据源配置
  datasource:
  #测试环境数据库配置
#    url: jdbc:mysql://47.75.120.118:3306/scenic_tool_db?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull
#    username: root
#    password: qwe1234
    #本地数据库
    url: jdbc:mysql://localhost:3306/zhly_db?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull
    username: root
    password: 123321
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
   ########### Druid 连接池配置  #############
    #连接池配置
    #Spring Boot中默认支持的连接池有dbcp,dbcp2, tomcat, hikari三种连接池,故需要特殊定制
    initialSize: 5
    minIdle: 5
    maxActive: 20
    validationQuery: SELECT 'x' FROM DUAL
    #配置获取连接等待超时的时间
    maxWait: 60000
    #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    #指定一个空闲连接最少空闲多久后可被清除，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    #当连接空闲时，是否执行连接测试
    testWhileIdle: true
    #当从连接池借用连接时，是否测试该连接
    testOnBorrow: false
    #在连接归还到连接池时是否测试该连接
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    #配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    #监控统计用的filter:stat日志用的filter:slf4j防御sql注入的filter:wall
    filters: stat,wall,slf4j
    maxPoolPreparedStatementPerConnectionSize: 20
    #通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

  data:
   mongodb:
     #测试环境
#      host: 120.25.228.180
#      port: 10001
#      username: dev
#      password: qwe123
#      #数据库名称
#      database: scenic-tool
#      #mongo验证
#      authenticationDatabase: admin
     #本地环境
      host: 127.0.0.1
      port: 27017
      database: kxp
      connectionsPerHost: 8
      threadsAllowedToBlockForConnectionMultiplier: 4
      connectTimeout: 5000
      maxWaitTime: 1500
      socketKeepAlive: true
      socketTimeout: 1500

  redis:
      ###Redis数据库索引（默认为0）
      database: 3
  #    host: 120.25.228.180
      host: 127.0.0.1
      port: 6379
      password:
      jedis:
        pool:
          ###连接池最大连接数（使用负值表示没有限制）
          max-active: 8
          ###连接池最大阻塞等待时间（使用负值表示没有限制）
          max-wait: -1
          ###连接池中的最大空闲连接
          max-idle: 5
          ###连接池中的最小空闲连接
          min-idle: 0
      ###连接超时时间（毫秒）
      timeout: 10000






